name: Echo Repository Commit Hash

on:
  push:
    branches:
      - main

jobs:
  echo-commit-hash:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Repository Commit Hash
      shell: pwsh
      run: |
        Write-Host "Repository Commit Hashh: $env:GITHUB_SHA"
