name: Echo All Environment Variables

on:
  push:
    branches:
      - main

jobs:
  echo-env-vars:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo All Environment Variables
      shell: pwsh
      run: |
        Get-ChildItem Env: | ForEach-Object { Write-Host "$($_.Name): $($_.Value)" }
