name: Echo Repository URL

on:
  push:
    branches:
      - main

jobs:
  echo-repo-url:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Repository URL
      shell: pwsh
      run: |
        $repo = $env:GITHUB_REPOSITORY
        $repoUrl = "https://github.com/$repo"
        Write-Host "Repository URL: $repoUrl"
