name: Echo Repository Directory

on:
  push:
    branches:
      - main

jobs:
  echo-repo-dir:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Echo Repository Directory
      shell: pwsh
      run: |
        Write-Host "Repository Directory: $env:GITHUB_WORKSPACE"
